### ISSUE TITLE
calibrate_pr2.py throws exception on shutdown  (ros ticket #3416)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_controllers#231]
{{{
Traceback (most recent call last):
  File "/u/watts/ros/pkgs/wg-ros-pkg-trunk/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 364, in <module>
    if **name** == '**main**': main()
  File "/u/watts/ros/pkgs/wg-ros-pkg-trunk/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 359, in main
    time.sleep(1e6)
KeyboardInterrupt
}}}

I launched and shutdown pr2.launch normally. Up-to-date on ROS, pkgs.

trac data:
- Owner: **sglaser**
- Reporter: **watts**
- Reported at: **Tue Jan  5 16:05:23 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/3416

**Comment by ahendrix** [comment]
[wim] Ken, is this the same problem we just saw in spawner?

**Comment by ahendrix** [comment]
[kwc] no, this is stu overriding rospy's signal handling and having to handle KeyboardInterrupts
