### ISSUE TITLE
Error connecting to ROS nodes with rospy, buffer size?  (ros ticket #920)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_controllers#30]
HysteresisControllerNode and SineSweepControllerNode for elbow flex joint open the controller and shut down instantly. The error message is as follows:

Traceback (most recent call last):
  File "/u/wgtest/ros/ros/core/rospy/src/rospy/tcpros_base.py", line 209, in _tcp_server_callback
    header = read_tcpros_header(sock, cStringIO.StringIO(), buff_size)
  File "/u/wgtest/ros/ros/core/rospy/src/rospy/tcpros_base.py", line 78, in read_tcpros_header
    raise TransportInitError("connection from sender terminated before header received")
TransportInitError: connection from sender terminated before header received

This works on elbow roll joints, but not elbow flex. Using wgtest account on tc5.

trac data:
- Owner: **kwc**
- Reporter: **watts**
- Reported at: **Mon Feb  2 19:31:53 2009**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/920

**Comment by ahendrix** [comment]
[kwc] is this still an issue?

**Comment by ahendrix** [comment]
[watts] Haven't seen it in a while, and the controllers work just fine. Not sure if I even filed this accurately, looks like this was on my first week as an intern.
